apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-operator-caddy-bootstrap
  namespace: dns-operator-system
  labels:
    app.kubernetes.io/name: dns-operator
    app.kubernetes.io/component: caddy
data:
  Caddyfile: |
    {
        admin off
        auto_https off
        log {
            output stdout
            format console
            level INFO
        }
    }

    import /etc/caddy/generated/*.caddy

    :2019 {
        respond /health "OK" 200
    }
