apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-operator-caddy
  namespace: dns-operator-system
  labels:
    app.kubernetes.io/name: dns-operator
    app.kubernetes.io/component: caddy
automountServiceAccountToken: false
