---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certificate.jerkytreats.dev
  resources:
  - certificatebundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certificate.jerkytreats.dev
  resources:
  - certificatebundles/finalizers
  verbs:
  - update
- apiGroups:
  - certificate.jerkytreats.dev
  resources:
  - certificatebundles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dns.jerkytreats.dev
  resources:
  - dnsrecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.jerkytreats.dev
  resources:
  - dnsrecords/finalizers
  verbs:
  - update
- apiGroups:
  - dns.jerkytreats.dev
  resources:
  - dnsrecords/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - publish.jerkytreats.dev
  resources:
  - publishedservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - publish.jerkytreats.dev
  resources:
  - publishedservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tailscale.jerkytreats.dev
  resources:
  - tailnetdnsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tailscale.jerkytreats.dev
  resources:
  - tailnetdnsconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - tailscale.jerkytreats.dev
  resources:
  - tailnetdnsconfigs/status
  verbs:
  - get
  - patch
  - update
